#!/bin/bash -e
# SSH into a kiosk pi using the generated ssh config file
# Usage: kiosk-ssh <pi-name> [ssh args]
# Example: kiosk-ssh test-kiosk "echo hello world"
script_dir="$(dirname -- "$( readlink -f -- "$0")")"
config_file="$script_dir/../generated/pi-ssh-config"

$script_dir/validate || exit 1

ssh -F $config_file "$@"
